import SwiftUI

struct ChineseColor: Identifiable, Hashable {
    let id = UUID()
    let name: String
    let pinyin: String
    let hex: String
    let category: ColorCategory

    var color: Color {
        cachedColor
    }

    var ns_color: NSColor {
        cachedNSColor
    }

    // Pre-cached SwiftUI Color to avoid repeated hex parsing
    private let cachedColor: Color
    // Pre-cached NSColor to avoid repeated hex parsing
    private let cachedNSColor: NSColor

    enum ColorCategory: String, CaseIterable {
        case group0 = "白月"
        case group1 = "朱砂"
        case group2 = "落霞"
        case group3 = "秋禾"
        case group4 = "苔青"
        case group5 = "柳烟"
        case group6 = "沧浪"
        case group7 = "晴岚"
        case group8 = "暮山"
        case group9 = "桃夭"
    }

    init(name: String, pinyin: String, hex: String, category: ColorCategory) {
        self.name = name
        self.pinyin = pinyin
        self.hex = hex
        self.category = category
        self.cachedColor = Color(hex: hex)
        self.cachedNSColor = NSColor(hex: hex) ?? .systemGreen
    }
}

// MARK: - Shared hex parsing

private struct RGBA {
    let r: UInt64
    let g: UInt64
    let b: UInt64
    let a: UInt64
}

/// Parse a hex string (3, 6, or 8 chars) into RGBA components.
/// Returns nil if parsing fails.
private func parseHex(_ hex: String) -> RGBA? {
    let cleaned = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
    var int: UInt64 = 0
    guard Scanner(string: cleaned).scanHexInt64(&int) else { return nil }
    switch cleaned.count {
    case 3:
        return RGBA(r: (int >> 8) * 17, g: (int >> 4 & 0xF) * 17, b: (int & 0xF) * 17, a: 255)
    case 6:
        return RGBA(r: int >> 16, g: int >> 8 & 0xFF, b: int & 0xFF, a: 255)
    case 8:
        return RGBA(r: int >> 24, g: int >> 16 & 0xFF, b: int >> 8 & 0xFF, a: int & 0xFF)
    default:
        return nil
    }
}

extension Color {
    init(hex: String) {
        if let rgba = parseHex(hex) {
            self.init(.sRGB, red: Double(rgba.r) / 255, green: Double(rgba.g) / 255, blue: Double(rgba.b) / 255, opacity: Double(rgba.a) / 255)
        } else {
            self.init(.sRGB, red: 0, green: 0, blue: 0, opacity: 1)
        }
    }
}

extension NSColor {
    convenience init?(hex: String) {
        guard let rgba = parseHex(hex) else { return nil }
        self.init(red: CGFloat(rgba.r) / 255, green: CGFloat(rgba.g) / 255, blue: CGFloat(rgba.b) / 255, alpha: CGFloat(rgba.a) / 255)
    }
}

struct ColorPalette {
    static let allColors: [ChineseColor] = [
        // 白月 (58 colors)
        ChineseColor(name: "殷红", pinyin: "yanhong", hex: "82111f", category: .group9),
        ChineseColor(name: "暗紫苑红", pinyin: "anziyuanhong", hex: "82202b", category: .group9),
        ChineseColor(name: "葡萄紫", pinyin: "putaozi", hex: "4c1f24", category: .group9),
        ChineseColor(name: "猪肝紫", pinyin: "zhuganzi", hex: "541e24", category: .group9),
        ChineseColor(name: "枣红", pinyin: "zaohong", hex: "7c1823", category: .group9),
        ChineseColor(name: "唐昌蒲红", pinyin: "tangchangpuhong", hex: "de1c31", category: .group9),
        ChineseColor(name: "枫叶红", pinyin: "fengyehong", hex: "c21f30", category: .group9),
        ChineseColor(name: "鹅冠红", pinyin: "eguanhong", hex: "d11a2d", category: .group9),
        ChineseColor(name: "莓红", pinyin: "meihong", hex: "c45a65", category: .group9),
        ChineseColor(name: "烟红", pinyin: "yanhong", hex: "894e54", category: .group9),
        ChineseColor(name: "苋菜红", pinyin: "xiancaihong", hex: "a61b29", category: .group9),
        ChineseColor(name: "春梅红", pinyin: "chunmeihong", hex: "f1939c", category: .group9),
        ChineseColor(name: "合欢红", pinyin: "hehuanhong", hex: "f0a1a8", category: .group9),
        ChineseColor(name: "鼠鼻红", pinyin: "shubihong", hex: "e3b4b8", category: .group9),
        ChineseColor(name: "满江红", pinyin: "manjianghong", hex: "a7535a", category: .group9),
        ChineseColor(name: "高梁红", pinyin: "gaolianghong", hex: "c02c38", category: .group9),
        ChineseColor(name: "茶花红", pinyin: "chahuahong", hex: "ee3f4d", category: .group9),
        ChineseColor(name: "玉红", pinyin: "yuhong", hex: "c04851", category: .group9),
        ChineseColor(name: "艳红", pinyin: "yanhong", hex: "ed5a65", category: .group9),
        ChineseColor(name: "葡萄酱紫", pinyin: "putaojiangzi", hex: "5a1216", category: .group9),
        ChineseColor(name: "香叶红", pinyin: "xiangyehong", hex: "f07c82", category: .group9),
        ChineseColor(name: "栗紫", pinyin: "lizi", hex: "5a191b", category: .group9),
        ChineseColor(name: "牡丹粉红", pinyin: "mudanfenhong", hex: "eea2a4", category: .group9),
        ChineseColor(name: "暗玉紫", pinyin: "anyuzi", hex: "5c2223", category: .group9),
        ChineseColor(name: "长石灰", pinyin: "changshihui", hex: "363433", category: .group0),
        ChineseColor(name: "蔫油绿", pinyin: "enyoulv", hex: "373834", category: .group0),
        ChineseColor(name: "瓦罐灰", pinyin: "waguanhui", hex: "47484c", category: .group0),
        ChineseColor(name: "黄昏灰", pinyin: "huanghunhui", hex: "474b4c", category: .group0),
        ChineseColor(name: "狼烟灰", pinyin: "langyanhui", hex: "5d655f", category: .group0),
        ChineseColor(name: "锌灰", pinyin: "xinhui", hex: "7a7374", category: .group0),
        ChineseColor(name: "嫩灰", pinyin: "nenhui", hex: "74787a", category: .group0),
        ChineseColor(name: "俄灰", pinyin: "ehui", hex: "737c7b", category: .group0),
        ChineseColor(name: "镊灰", pinyin: "niehui", hex: "9fa39a", category: .group0),
        ChineseColor(name: "冰山蓝", pinyin: "bingshanlan", hex: "a4aca7", category: .group0),
        ChineseColor(name: "星灰", pinyin: "xinghui", hex: "b2bbbe", category: .group0),
        ChineseColor(name: "月影白", pinyin: "yueyingbai", hex: "c0c4c3", category: .group0),
        ChineseColor(name: "玛瑙灰", pinyin: "manaohui", hex: "cfccc9", category: .group0),
        ChineseColor(name: "大理石灰", pinyin: "dalishihui", hex: "c4cbcf", category: .group0),
        ChineseColor(name: "银鱼白", pinyin: "yinyubai", hex: "cdd1d3", category: .group0),
        ChineseColor(name: "艾绿", pinyin: "ailv", hex: "cad3c3", category: .group0),
        ChineseColor(name: "鸥蓝", pinyin: "oulan", hex: "c7d2d4", category: .group0),
        ChineseColor(name: "远山紫", pinyin: "yuanshanzi", hex: "ccccd6", category: .group0),
        ChineseColor(name: "浅灰", pinyin: "qianhui", hex: "dad4cb", category: .group0),
        ChineseColor(name: "千食白", pinyin: "qianshibai", hex: "e2e1e4", category: .group0),
        ChineseColor(name: "珍珠灰", pinyin: "zhenzhuhui", hex: "e4dfd7", category: .group0),
        ChineseColor(name: "云峰白", pinyin: "yunfengbai", hex: "d8e3e7", category: .group0),
        ChineseColor(name: "丁香淡紫", pinyin: "dingxiangdanzi", hex: "e9d7df", category: .group0),
        ChineseColor(name: "马鞭草紫", pinyin: "mabiancaozi", hex: "ede3e7", category: .group0),
        ChineseColor(name: "银白", pinyin: "yinbai", hex: "f1f0ed", category: .group0),
        ChineseColor(name: "淡藤萝紫", pinyin: "dantengluozi", hex: "f2e7e5", category: .group0),
        ChineseColor(name: "嫩菊绿", pinyin: "nenjulv", hex: "f0f5e5", category: .group0),
        ChineseColor(name: "月白", pinyin: "yuebai", hex: "eef7f2", category: .group0),
        ChineseColor(name: "鱼肚白", pinyin: "yudubai", hex: "f7f4ed", category: .group0),
        ChineseColor(name: "草珠红", pinyin: "caozhuhong", hex: "f8ebe6", category: .group0),
        ChineseColor(name: "汉白玉", pinyin: "hanbaiyu", hex: "f8f4ed", category: .group0),
        ChineseColor(name: "海参灰", pinyin: "haishenhui", hex: "fffefa", category: .group0),
        ChineseColor(name: "象牙白", pinyin: "xiangyabai", hex: "fffef8", category: .group0),
        ChineseColor(name: "雪白", pinyin: "xuebai", hex: "fffef9", category: .group0),

        // 朱砂 (52 colors)
        ChineseColor(name: "淡铁灰", pinyin: "dantiehui", hex: "5b423a", category: .group1),
        ChineseColor(name: "淡桃红", pinyin: "dantaohong", hex: "f6cec1", category: .group1),
        ChineseColor(name: "淡豆沙", pinyin: "dandousha", hex: "873d24", category: .group1),
        ChineseColor(name: "蟹毛红", pinyin: "xiemaohong", hex: "b14b28", category: .group1),
        ChineseColor(name: "椰壳棕", pinyin: "yekezong", hex: "883a1e", category: .group1),
        ChineseColor(name: "中灰驼", pinyin: "zhonghuituo", hex: "603d30", category: .group1),
        ChineseColor(name: "咖啡", pinyin: "kafei", hex: "753117", category: .group1),
        ChineseColor(name: "法螺红", pinyin: "faluohong", hex: "ee8055", category: .group1),
        ChineseColor(name: "落霞红", pinyin: "luoxiahong", hex: "cf4813", category: .group1),
        ChineseColor(name: "芙蓉红", pinyin: "furonghong", hex: "f9723d", category: .group1),
        ChineseColor(name: "珠母灰", pinyin: "zhumuhui", hex: "64483d", category: .group1),
        ChineseColor(name: "淡土黄", pinyin: "dantuhuang", hex: "8c4b31", category: .group1),
        ChineseColor(name: "龙睛鱼红", pinyin: "longjingyuhong", hex: "ef632b", category: .group1),
        ChineseColor(name: "润红", pinyin: "runhong", hex: "f7cdbc", category: .group1),
        ChineseColor(name: "笋皮棕", pinyin: "sunpizong", hex: "732e12", category: .group1),
        ChineseColor(name: "淡藏花红", pinyin: "dancanghuahong", hex: "f6ad8f", category: .group1),
        ChineseColor(name: "瓜瓤红", pinyin: "guaranghong", hex: "f68c60", category: .group1),
        ChineseColor(name: "淡玫瑰灰", pinyin: "danmeiguihui", hex: "b89485", category: .group1),
        ChineseColor(name: "丁香棕", pinyin: "dingxiangzong", hex: "71361d", category: .group1),
        ChineseColor(name: "莓酱红", pinyin: "meijianghong", hex: "fa5d19", category: .group1),
        ChineseColor(name: "干红", pinyin: "ganhong", hex: "a6522c", category: .group1),
        ChineseColor(name: "火泥棕", pinyin: "huonizong", hex: "aa6a4c", category: .group1),
        ChineseColor(name: "中红灰", pinyin: "zhonghonghui", hex: "8b614d", category: .group1),
        ChineseColor(name: "藕荷", pinyin: "ouhe", hex: "edc3ae", category: .group1),
        ChineseColor(name: "野蔷薇红", pinyin: "yeqiangweihong", hex: "fb9968", category: .group1),
        ChineseColor(name: "玉粉红", pinyin: "yufenhong", hex: "e8b49a", category: .group1),
        ChineseColor(name: "晨曦红", pinyin: "chenxihong", hex: "ea8958", category: .group1),
        ChineseColor(name: "燕颔红", pinyin: "yanhanhong", hex: "fc6315", category: .group1),
        ChineseColor(name: "淡可可棕", pinyin: "dankekezong", hex: "b7511d", category: .group1),
        ChineseColor(name: "金驼", pinyin: "jintuo", hex: "e46828", category: .group1),
        ChineseColor(name: "蟹壳红", pinyin: "xiekehong", hex: "f27635", category: .group1),
        ChineseColor(name: "介壳淡粉红", pinyin: "jieqiaodanfenhong", hex: "f7cfba", category: .group1),
        ChineseColor(name: "铁棕", pinyin: "tiezong", hex: "d85916", category: .group1),
        ChineseColor(name: "初桃粉红", pinyin: "chutaofenhong", hex: "f6dcce", category: .group1),
        ChineseColor(name: "火砖红", pinyin: "huozhuanhong", hex: "cd6227", category: .group1),
        ChineseColor(name: "金莲花橙", pinyin: "jinlianhuacheng", hex: "f86b1d", category: .group1),
        ChineseColor(name: "余烬红", pinyin: "yujinhong", hex: "cf7543", category: .group1),
        ChineseColor(name: "菠萝红", pinyin: "boluohong", hex: "fc7930", category: .group1),
        ChineseColor(name: "陶瓷红", pinyin: "taocihong", hex: "e16723", category: .group1),
        ChineseColor(name: "芒果棕", pinyin: "mangguozong", hex: "954416", category: .group1),
        ChineseColor(name: "岩石棕", pinyin: "yanshizong", hex: "964d22", category: .group1),
        ChineseColor(name: "海螺橙", pinyin: "hailuocheng", hex: "f0945d", category: .group1),
        ChineseColor(name: "淡咖啡", pinyin: "dankafei", hex: "945833", category: .group1),
        ChineseColor(name: "蛛网灰", pinyin: "zhuwanghui", hex: "b7a091", category: .group1),
        ChineseColor(name: "米色", pinyin: "mise", hex: "f9e9cd", category: .group0),
        ChineseColor(name: "美人焦橙", pinyin: "meirenjiaocheng", hex: "fa7e23", category: .group1),
        ChineseColor(name: "玫瑰粉", pinyin: "meiguifen", hex: "f8b37f", category: .group1),
        ChineseColor(name: "金黄", pinyin: "jinhuang", hex: "f26b1f", category: .group1),
        ChineseColor(name: "橘橙", pinyin: "jucheng", hex: "f97d1c", category: .group1),
        ChineseColor(name: "鳜鱼红", pinyin: "guiyuhong", hex: "f09c5a", category: .group1),
        ChineseColor(name: "雁灰", pinyin: "yanhui", hex: "80766e", category: .group0),
        ChineseColor(name: "醉瓜肉", pinyin: "zuiguarou", hex: "db8540", category: .group1),

        // 落霞 (52 colors)
        ChineseColor(name: "柘黄", pinyin: "jizong", hex: "de7622", category: .group2),
        ChineseColor(name: "古铜褐", pinyin: "gutonghe", hex: "5c3719", category: .group2),
        ChineseColor(name: "淡赭", pinyin: "danzhe", hex: "be7e4a", category: .group2),
        ChineseColor(name: "晓灰", pinyin: "xiaohui", hex: "d4c4b7", category: .group2),
        ChineseColor(name: "槟榔棕", pinyin: "binglangzong", hex: "c1651a", category: .group2),
        ChineseColor(name: "鹿皮褐", pinyin: "lupihe", hex: "d99156", category: .group2),
        ChineseColor(name: "银灰", pinyin: "yinhui", hex: "918072", category: .group2),
        ChineseColor(name: "驼色", pinyin: "tuose", hex: "66462a", category: .group2),
        ChineseColor(name: "茶褐", pinyin: "chahe", hex: "5d3d21", category: .group2),
        ChineseColor(name: "海鸥灰", pinyin: "haiouhui", hex: "9a8878", category: .group2),
        ChineseColor(name: "深灰", pinyin: "shenhui", hex: "81776e", category: .group2),
        ChineseColor(name: "淡米粉", pinyin: "danmifen", hex: "fbeee2", category: .group0),
        ChineseColor(name: "松鼠灰", pinyin: "songshuhui", hex: "4f4032", category: .group2),
        ChineseColor(name: "荷花粉", pinyin: "hehuabai", hex: "fbecde", category: .group2),
        ChineseColor(name: "北瓜黄", pinyin: "beiguahuang", hex: "fc8c23", category: .group2),
        ChineseColor(name: "夜灰", pinyin: "yehui", hex: "847c74", category: .group2),
        ChineseColor(name: "淡银灰", pinyin: "danyinhui", hex: "c1b2a3", category: .group2),
        ChineseColor(name: "瓦灰", pinyin: "wahui", hex: "867e76", category: .group2),
        ChineseColor(name: "鹤灰", pinyin: "hehui", hex: "4a4035", category: .group2),
        ChineseColor(name: "橄榄灰", pinyin: "ganlanhui", hex: "503e2a", category: .group2),
        ChineseColor(name: "杏黄", pinyin: "xinghuang", hex: "f28e16", category: .group2),
        ChineseColor(name: "中灰", pinyin: "zhonghui", hex: "a49c93", category: .group2),
        ChineseColor(name: "蛋壳黄", pinyin: "dankehuang", hex: "f8c387", category: .group2),
        ChineseColor(name: "万寿菊黄", pinyin: "wanshoujuhuang", hex: "fb8b05", category: .group2),
        ChineseColor(name: "淡松烟", pinyin: "dansongyan", hex: "4d4030", category: .group2),
        ChineseColor(name: "鹿角棕", pinyin: "lujiaozong", hex: "e3bd8d", category: .group2),
        ChineseColor(name: "猴毛灰", pinyin: "houmaohui", hex: "97846c", category: .group2),
        ChineseColor(name: "山鸡褐", pinyin: "shanjihe", hex: "986524", category: .group2),
        ChineseColor(name: "蟹壳绿", pinyin: "xiekelv", hex: "513c20", category: .group2),
        ChineseColor(name: "焦茶绿", pinyin: "jiaochalv", hex: "553b18", category: .group2),
        ChineseColor(name: "玳瑁黄", pinyin: "daimaohuang", hex: "daa45a", category: .group2),
        ChineseColor(name: "柚黄", pinyin: "liuehuang", hex: "f9a633", category: .group2),
        ChineseColor(name: "瓜瓤粉", pinyin: "guarangfen", hex: "f9cb8b", category: .group2),
        ChineseColor(name: "软木黄", pinyin: "ruanmuhuang", hex: "de9e44", category: .group2),
        ChineseColor(name: "落英淡粉", pinyin: "luoyingdanfen", hex: "f9e8d0", category: .group2),
        ChineseColor(name: "古铜绿", pinyin: "gutonglv", hex: "533c1b", category: .group2),
        ChineseColor(name: "凋叶棕", pinyin: "diaoyezong", hex: "e7a23f", category: .group2),
        ChineseColor(name: "肉色", pinyin: "rouse", hex: "f7c173", category: .group2),
        ChineseColor(name: "金莺黄", pinyin: "jinyinghuang", hex: "f4a83a", category: .group2),
        ChineseColor(name: "风帆黄", pinyin: "fengfanhuang", hex: "dc9123", category: .group2),
        ChineseColor(name: "桂皮淡棕", pinyin: "guipidanzong", hex: "c09351", category: .group2),
        ChineseColor(name: "蜜黄", pinyin: "mihuang", hex: "fbb957", category: .group2),
        ChineseColor(name: "雄黄", pinyin: "xionghuang", hex: "ff9900", category: .group2),
        ChineseColor(name: "铅灰", pinyin: "qianhui", hex: "bbb5ac", category: .group2),
        ChineseColor(name: "龟背黄", pinyin: "guibeihuang", hex: "826b48", category: .group2),
        ChineseColor(name: "淡橘橙", pinyin: "danjucheng", hex: "fba414", category: .group2),
        ChineseColor(name: "粉白", pinyin: "fenbai", hex: "fbf2e3", category: .group0),
        ChineseColor(name: "苍黄", pinyin: "canghuang", hex: "806332", category: .group2),
        ChineseColor(name: "金叶黄", pinyin: "jinyehuang", hex: "ffa60f", category: .group2),
        ChineseColor(name: "枇杷黄", pinyin: "pipahuang", hex: "fca106", category: .group2),
        ChineseColor(name: "莱阳梨黄", pinyin: "laiyanglihuang", hex: "815f25", category: .group2),
        ChineseColor(name: "橙皮黄", pinyin: "chengpihuang", hex: "fca104", category: .group2),

        // 秋禾 (52 colors)
        ChineseColor(name: "彝绿", pinyin: "yililv", hex: "835e1d", category: .group3),
        ChineseColor(name: "淡肉色", pinyin: "danrouse", hex: "f8e0b0", category: .group3),
        ChineseColor(name: "河豚灰", pinyin: "hetunhui", hex: "393733", category: .group0),
        ChineseColor(name: "荔肉白", pinyin: "liroubai", hex: "f2e6ce", category: .group0),
        ChineseColor(name: "酪黄", pinyin: "laohuang", hex: "f6dead", category: .group3),
        ChineseColor(name: "百灵鸟灰", pinyin: "bailingniaohui", hex: "b4a992", category: .group0),
        ChineseColor(name: "浅土色", pinyin: "qiantuose", hex: "e2c17c", category: .group3),
        ChineseColor(name: "麦芽糖黄", pinyin: "maiyatanghuang", hex: "f9d27d", category: .group3),
        ChineseColor(name: "鹅掌黄", pinyin: "ezhanghuang", hex: "fbb929", category: .group3),
        ChineseColor(name: "燕羽灰", pinyin: "yanyuhui", hex: "685e48", category: .group3),
        ChineseColor(name: "甘草黄", pinyin: "gancaohuang", hex: "f3bf4c", category: .group3),
        ChineseColor(name: "沙石黄", pinyin: "shashihuang", hex: "e5b751", category: .group3),
        ChineseColor(name: "蟹壳灰", pinyin: "xiekehui", hex: "695e45", category: .group3),
        ChineseColor(name: "莲子白", pinyin: "lianzibai", hex: "e5d3aa", category: .group0),
        ChineseColor(name: "山鸡黄", pinyin: "shanjihuang", hex: "b78b26", category: .group3),
        ChineseColor(name: "初熟杏黄", pinyin: "chushuxinghuang", hex: "f8bc31", category: .group3),
        ChineseColor(name: "银鼠灰", pinyin: "yinshuhui", hex: "b5aa90", category: .group0),
        ChineseColor(name: "鸡蛋黄", pinyin: "jidanhuang", hex: "fbb612", category: .group3),
        ChineseColor(name: "虎皮黄", pinyin: "hupihuang", hex: "eaad1a", category: .group3),
        ChineseColor(name: "香水玫瑰黄", pinyin: "xiangshuimeiguihuang", hex: "f7da94", category: .group3),
        ChineseColor(name: "土黄", pinyin: "tuhuang", hex: "d6a01d", category: .group3),
        ChineseColor(name: "豆汁黄", pinyin: "douzhihuang", hex: "f8e8c1", category: .group3),
        ChineseColor(name: "礁青", pinyin: "jiaoqing", hex: "87723e", category: .group3),
        ChineseColor(name: "象牙黄", pinyin: "xiangyahuang", hex: "f0d695", category: .group3),
        ChineseColor(name: "鼸黄", pinyin: "youhuang", hex: "fcb70a", category: .group3),
        ChineseColor(name: "尘灰", pinyin: "chenhui", hex: "b6a476", category: .group3),
        ChineseColor(name: "棕叶绿", pinyin: "zongyelv", hex: "876818", category: .group3),
        ChineseColor(name: "灰绿", pinyin: "huilv", hex: "8a6913", category: .group3),
        ChineseColor(name: "琥珀黄", pinyin: "hupohuang", hex: "feba07", category: .group3),
        ChineseColor(name: "炒米黄", pinyin: "chaomihuang", hex: "f4ce69", category: .group3),
        ChineseColor(name: "蚌肉白", pinyin: "bangroubai", hex: "f9f1db", category: .group0),
        ChineseColor(name: "篾黄", pinyin: "miehuang", hex: "f7de98", category: .group3),
        ChineseColor(name: "暗海水绿", pinyin: "anhaishuilv", hex: "584717", category: .group3),
        ChineseColor(name: "栀子黄", pinyin: "zhizihuang", hex: "ebb10d", category: .group3),
        ChineseColor(name: "芥黄", pinyin: "jiehuang", hex: "d9a40e", category: .group3),
        ChineseColor(name: "淡密黄", pinyin: "danmihuang", hex: "f9d367", category: .group3),
        ChineseColor(name: "浅烙黄", pinyin: "qianlaohuang", hex: "f9bd10", category: .group3),
        ChineseColor(name: "枯绿", pinyin: "kulv", hex: "b78d12", category: .group3),
        ChineseColor(name: "樱桃冠黄", pinyin: "yingwuguanhuang", hex: "f6c430", category: .group3),
        ChineseColor(name: "棕榈绿", pinyin: "zonglvlv", hex: "5b4913", category: .group3),
        ChineseColor(name: "雅梨黄", pinyin: "yalihuang", hex: "fbc82f", category: .group3),
        ChineseColor(name: "淡藤黄", pinyin: "danjianhuang", hex: "f9d770", category: .group3),
        ChineseColor(name: "木瓜黄", pinyin: "muguahuang", hex: "f9c116", category: .group3),
        ChineseColor(name: "谷黄", pinyin: "guhuang", hex: "e8b004", category: .group3),
        ChineseColor(name: "杏仁黄", pinyin: "xingrenhuang", hex: "f7e8aa", category: .group3),
        ChineseColor(name: "黄连黄", pinyin: "huanglianhuang", hex: "fcc515", category: .group3),
        ChineseColor(name: "菊蕾白", pinyin: "juleibai", hex: "e9ddb6", category: .group0),
        ChineseColor(name: "金盏黄", pinyin: "jinzhanhuang", hex: "fcc307", category: .group3),
        ChineseColor(name: "大豆黄", pinyin: "dadouhuang", hex: "fbcd31", category: .group3),
        ChineseColor(name: "葵扇黄", pinyin: "kuishanhuang", hex: "f8d86a", category: .group3),
        ChineseColor(name: "月灰", pinyin: "yuehui", hex: "b7ae8f", category: .group0),
        ChineseColor(name: "乳鸭黄", pinyin: "ruyahuang", hex: "ffc90c", category: .group3),

        // 苔青 (52 colors)
        ChineseColor(name: "素馨黄", pinyin: "suxinhuang", hex: "fccb16", category: .group4),
        ChineseColor(name: "向日葵黄", pinyin: "xiangrikuihuang", hex: "fecc11", category: .group4),
        ChineseColor(name: "草灰绿", pinyin: "caohuilv", hex: "8e804b", category: .group3),
        ChineseColor(name: "柠檬黄", pinyin: "ningmenghuang", hex: "fcd337", category: .group4),
        ChineseColor(name: "苔绿", pinyin: "tailv", hex: "887322", category: .group4),
        ChineseColor(name: "碧螺春绿", pinyin: "biluochunlv", hex: "867018", category: .group4),
        ChineseColor(name: "芒果黄", pinyin: "mangguohuang", hex: "ddc871", category: .group4),
        ChineseColor(name: "藤黄", pinyin: "tenghuang", hex: "ffd111", category: .group4),
        ChineseColor(name: "茺苜黄", pinyin: "molihuang", hex: "f8df72", category: .group4),
        ChineseColor(name: "蒿黄", pinyin: "haohuang", hex: "dfc243", category: .group4),
        ChineseColor(name: "麦杆黄", pinyin: "maiganhuang", hex: "f8df70", category: .group4),
        ChineseColor(name: "金瓜黄", pinyin: "jinguahuang", hex: "fcd217", category: .group4),
        ChineseColor(name: "姜黄", pinyin: "jianghuang", hex: "e2c027", category: .group4),
        ChineseColor(name: "潭水绿", pinyin: "tanshuilv", hex: "645822", category: .group4),
        ChineseColor(name: "硫华黄", pinyin: "liuhuahuang", hex: "f2ce2b", category: .group4),
        ChineseColor(name: "草黄", pinyin: "caohuang", hex: "d2b42c", category: .group4),
        ChineseColor(name: "柚黄", pinyin: "youhuang", hex: "f1ca17", category: .group4),
        ChineseColor(name: "秋葵黄", pinyin: "qiukuihuang", hex: "eed045", category: .group4),
        ChineseColor(name: "油菜花黄", pinyin: "youcaihuahuang", hex: "fbda41", category: .group4),
        ChineseColor(name: "新禾绿", pinyin: "xinhelv", hex: "d2b116", category: .group4),
        ChineseColor(name: "香蕉黄", pinyin: "xiangjiaohuang", hex: "e4bf11", category: .group4),
        ChineseColor(name: "乳白", pinyin: "rubai", hex: "f9f4dc", category: .group0),
        ChineseColor(name: "佛手黄", pinyin: "foshouhuang", hex: "fed71a", category: .group4),
        ChineseColor(name: "淡灰绿", pinyin: "danhuilv", hex: "ad9e5f", category: .group4),
        ChineseColor(name: "橄榄绿", pinyin: "ganlanlv", hex: "5e5314", category: .group4),
        ChineseColor(name: "蝶黄", pinyin: "diehuang", hex: "e2d849", category: .group4),
        ChineseColor(name: "槐花黄绿", pinyin: "huaihuahuanglv", hex: "d2d97a", category: .group4),
        ChineseColor(name: "橄榄黄绿", pinyin: "ganlanhuanglv", hex: "bec936", category: .group4),
        ChineseColor(name: "海茫茫绿", pinyin: "haimeilv", hex: "e2e7bf", category: .group4),
        ChineseColor(name: "苹果绿", pinyin: "pingguolv", hex: "bacf65", category: .group4),
        ChineseColor(name: "姚黄", pinyin: "yaohuang", hex: "d0deaa", category: .group4),
        ChineseColor(name: "芦苇绿", pinyin: "luweilv", hex: "b7d07a", category: .group4),
        ChineseColor(name: "芽绿", pinyin: "yalv", hex: "96c24e", category: .group4),
        ChineseColor(name: "橄榄石绿", pinyin: "ganlanshilv", hex: "b2cf87", category: .group4),
        ChineseColor(name: "艾背绿", pinyin: "aibeilv", hex: "dfecd5", category: .group4),
        ChineseColor(name: "樱桃绿", pinyin: "yingwulv", hex: "5bae23", category: .group4),
        ChineseColor(name: "水绿", pinyin: "shuilv", hex: "8cc269", category: .group4),
        ChineseColor(name: "田螺绿", pinyin: "tianluolv", hex: "5e665b", category: .group4),
        ChineseColor(name: "嘉陵水绿", pinyin: "jialingshuilv", hex: "add5a2", category: .group4),
        ChineseColor(name: "宝石绿", pinyin: "baoshilv", hex: "41ae3c", category: .group4),
        ChineseColor(name: "油绿", pinyin: "youlv", hex: "253d24", category: .group4),
        ChineseColor(name: "鲜绿", pinyin: "xianlv", hex: "43b244", category: .group4),
        ChineseColor(name: "玉簪绿", pinyin: "yusuilv", hex: "41b349", category: .group4),
        ChineseColor(name: "淡翠绿", pinyin: "dancuilv", hex: "c6dfc8", category: .group4),
        ChineseColor(name: "榺寄生绿", pinyin: "hujishenglv", hex: "2b312c", category: .group4),
        ChineseColor(name: "瓦松绿", pinyin: "wasonglv", hex: "6e8b74", category: .group4),
        ChineseColor(name: "白屈菜绿", pinyin: "baiqucailv", hex: "485b4d", category: .group4),
        ChineseColor(name: "松霜绿", pinyin: "songshuanglv", hex: "83a78d", category: .group4),
        ChineseColor(name: "明绿", pinyin: "minglv", hex: "9eccab", category: .group4),
        ChineseColor(name: "明灰", pinyin: "minghui", hex: "8a988e", category: .group4),
        ChineseColor(name: "毛绿", pinyin: "maolv", hex: "66c18c", category: .group4),
        ChineseColor(name: "宫殿绿", pinyin: "gongdianlv", hex: "20894d", category: .group4),

        // 柳烟 (52 colors)
        ChineseColor(name: "云杉绿", pinyin: "yunshanlv", hex: "15231b", category: .group5),
        ChineseColor(name: "孔省绿", pinyin: "kongquelv", hex: "229453", category: .group5),
        ChineseColor(name: "竹篁绿", pinyin: "zhuhuanglv", hex: "b9dec9", category: .group5),
        ChineseColor(name: "蛋白石绿", pinyin: "danbaishilv", hex: "579572", category: .group5),
        ChineseColor(name: "薄荷绿", pinyin: "bohelv", hex: "207f4c", category: .group5),
        ChineseColor(name: "蔻梢绿", pinyin: "koushaolv", hex: "5dbe8a", category: .group5),
        ChineseColor(name: "蝉绿", pinyin: "chanlv", hex: "3c9566", category: .group5),
        ChineseColor(name: "玉簪绿", pinyin: "yuzanlv", hex: "a4cab6", category: .group5),
        ChineseColor(name: "田园绿", pinyin: "tianyuanlv", hex: "68b88e", category: .group5),
        ChineseColor(name: "淡绿", pinyin: "danlv", hex: "61ac85", category: .group5),
        ChineseColor(name: "荷叶绿", pinyin: "heyelv", hex: "1a6840", category: .group5),
        ChineseColor(name: "葱绿", pinyin: "conglv", hex: "40a070", category: .group5),
        ChineseColor(name: "翠绿", pinyin: "cuilv", hex: "20a162", category: .group5),
        ChineseColor(name: "麦苗绿", pinyin: "maimiaolv", hex: "55bb8a", category: .group5),
        ChineseColor(name: "淡绿灰", pinyin: "danlvhui", hex: "70887d", category: .group5),
        ChineseColor(name: "粉绿", pinyin: "fenlv", hex: "83cbac", category: .group5),
        ChineseColor(name: "橄榄绿", pinyin: "ganlanlv", hex: "1f2623", category: .group5),
        ChineseColor(name: "浪花绿", pinyin: "langhualv", hex: "92b3a5", category: .group5),
        ChineseColor(name: "蛙绿", pinyin: "walv", hex: "45b787", category: .group5),
        ChineseColor(name: "草原远绿", pinyin: "caoyuanyuanlv", hex: "9abeaf", category: .group5),
        ChineseColor(name: "铜绿", pinyin: "tonglv", hex: "2bae85", category: .group5),
        ChineseColor(name: "梧枝绿", pinyin: "wuzhilv", hex: "69a794", category: .group5),
        ChineseColor(name: "莽丛绿", pinyin: "mangconglv", hex: "141e1b", category: .group5),
        ChineseColor(name: "飞泉绿", pinyin: "feiquanlv", hex: "497568", category: .group5),
        ChineseColor(name: "苍绿", pinyin: "canglv", hex: "223e36", category: .group5),
        ChineseColor(name: "青矾绿", pinyin: "qingfanlv", hex: "2c9678", category: .group5),
        ChineseColor(name: "绿灰", pinyin: "lvhui", hex: "314a43", category: .group5),
        ChineseColor(name: "深海绿", pinyin: "shenhailv", hex: "1a3b32", category: .group5),
        ChineseColor(name: "海王绿", pinyin: "haiwanglv", hex: "248067", category: .group5),
        ChineseColor(name: "竹绿", pinyin: "zhulv", hex: "1ba784", category: .group5),
        ChineseColor(name: "亚丁绿", pinyin: "yadinglv", hex: "428675", category: .group5),
        ChineseColor(name: "蓝绿", pinyin: "lanlv", hex: "12a182", category: .group5),
        ChineseColor(name: "美蝶绿", pinyin: "meidielv", hex: "12aa9c", category: .group5),
        ChineseColor(name: "穹灰", pinyin: "qionghui", hex: "c4d7d6", category: .group5),
        ChineseColor(name: "石绿", pinyin: "shilv", hex: "57c3c2", category: .group5),
        ChineseColor(name: "虾壳青", pinyin: "xiakeqing", hex: "869d9d", category: .group5),
        ChineseColor(name: "海天蓝", pinyin: "haitianlan", hex: "c6e6e8", category: .group5),
        ChineseColor(name: "夏云灰", pinyin: "xiayunhui", hex: "617172", category: .group5),
        ChineseColor(name: "清水蓝", pinyin: "qingshuilan", hex: "93d5dc", category: .group5),
        ChineseColor(name: "晚波蓝", pinyin: "wanbolan", hex: "648e93", category: .group5),
        ChineseColor(name: "甸子蓝", pinyin: "dianzilan", hex: "10aec2", category: .group5),
        ChineseColor(name: "闪蓝", pinyin: "shanlan", hex: "7cabb1", category: .group5),
        ChineseColor(name: "瀑布蓝", pinyin: "pubulan", hex: "51c4d3", category: .group5),
        ChineseColor(name: "蔚蓝", pinyin: "weilan", hex: "29b7cb", category: .group5),
        ChineseColor(name: "孔省蓝", pinyin: "kongquelan", hex: "0eb0c9", category: .group5),
        ChineseColor(name: "蜻蜓蓝", pinyin: "qingtinglan", hex: "3b818c", category: .group5),
        ChineseColor(name: "翠蓝", pinyin: "cuilan", hex: "1e9eb3", category: .group5),
        ChineseColor(name: "桧鸟蓝", pinyin: "jianniaolan", hex: "1491a8", category: .group5),
        ChineseColor(name: "胆矾蓝", pinyin: "danfanlan", hex: "0f95b0", category: .group5),
        ChineseColor(name: "玉珉蓝", pinyin: "yuqinlan", hex: "126e82", category: .group5),
        ChineseColor(name: "霁青", pinyin: "jiqing", hex: "63bbd0", category: .group5),
        ChineseColor(name: "海青", pinyin: "haiqing", hex: "22a2c3", category: .group5),

        // 沧浪 (52 colors)
        ChineseColor(name: "湖水蓝", pinyin: "hushuilan", hex: "b0d5df", category: .group6),
        ChineseColor(name: "灰蓝", pinyin: "huilan", hex: "21373d", category: .group6),
        ChineseColor(name: "深灰蓝", pinyin: "shenhuilan", hex: "132c33", category: .group6),
        ChineseColor(name: "苍蓝", pinyin: "canglan", hex: "134857", category: .group6),
        ChineseColor(name: "碧青", pinyin: "biqing", hex: "5cb3cc", category: .group6),
        ChineseColor(name: "钴蓝", pinyin: "gulan", hex: "1a94bc", category: .group6),
        ChineseColor(name: "鸢尾蓝", pinyin: "yuanweilan", hex: "158bb8", category: .group6),
        ChineseColor(name: "井天蓝", pinyin: "jingtianlan", hex: "c3d7df", category: .group6),
        ChineseColor(name: "秋波蓝", pinyin: "qiubolan", hex: "8abcd1", category: .group6),
        ChineseColor(name: "云山蓝", pinyin: "yunshanlan", hex: "2f90b9", category: .group6),
        ChineseColor(name: "远天蓝", pinyin: "yuantianlan", hex: "d0dfe6", category: .group6),
        ChineseColor(name: "涧石蓝", pinyin: "jianshilan", hex: "66a9c9", category: .group6),
        ChineseColor(name: "油蓝", pinyin: "youlan", hex: "1781b5", category: .group6),
        ChineseColor(name: "淡蓝灰", pinyin: "danlanhui", hex: "5e7987", category: .group6),
        ChineseColor(name: "宝石蓝", pinyin: "baoshilan", hex: "2486b9", category: .group6),
        ChineseColor(name: "牵牛花蓝", pinyin: "qianniuhualan", hex: "1177b0", category: .group6),
        ChineseColor(name: "天蓝", pinyin: "tianlan", hex: "1677b3", category: .group6),
        ChineseColor(name: "潮蓝", pinyin: "chaolan", hex: "2983bb", category: .group6),
        ChineseColor(name: "搪磁蓝", pinyin: "tangcilan", hex: "11659a", category: .group6),
        ChineseColor(name: "睛蓝", pinyin: "jinglan", hex: "5698c3", category: .group6),
        ChineseColor(name: "晴山蓝", pinyin: "qingshanlan", hex: "8fb2c9", category: .group6),
        ChineseColor(name: "战舰灰", pinyin: "zhanjianhui", hex: "495c69", category: .group6),
        ChineseColor(name: "羽扇豆蓝", pinyin: "yushandoulan", hex: "619ac3", category: .group6),
        ChineseColor(name: "云水蓝", pinyin: "yunshuilan", hex: "baccd9", category: .group6),
        ChineseColor(name: "群青", pinyin: "qunqing", hex: "1772b4", category: .group6),
        ChineseColor(name: "柏林蓝", pinyin: "bolinlan", hex: "126bae", category: .group6),
        ChineseColor(name: "虹蓝", pinyin: "honglan", hex: "2177b8", category: .group6),
        ChineseColor(name: "星蓝", pinyin: "xinglan", hex: "93b5cf", category: .group6),
        ChineseColor(name: "燕蓝", pinyin: "yanlan", hex: "144a74", category: .group6),
        ChineseColor(name: "花青", pinyin: "huaqing", hex: "2376b7", category: .group6),
        ChineseColor(name: "蝶翅蓝", pinyin: "diechilan", hex: "4e7ca1", category: .group6),
        ChineseColor(name: "尼罗蓝", pinyin: "niluolan", hex: "2474b5", category: .group6),
        ChineseColor(name: "景泰蓝", pinyin: "jingtailan", hex: "2775b6", category: .group6),
        ChineseColor(name: "品蓝", pinyin: "pinlan", hex: "2b73af", category: .group6),
        ChineseColor(name: "海军蓝", pinyin: "haijunlan", hex: "346c9c", category: .group6),
        ChineseColor(name: "安安蓝", pinyin: "ananlan", hex: "3170a7", category: .group6),
        ChineseColor(name: "甸青", pinyin: "dianqing", hex: "1661ab", category: .group6),
        ChineseColor(name: "飞燕草蓝", pinyin: "feiyancaolan", hex: "0f59a4", category: .group6),
        ChineseColor(name: "海涛蓝", pinyin: "haitaolan", hex: "15559a", category: .group6),
        ChineseColor(name: "钢青", pinyin: "gangqing", hex: "142334", category: .group6),
        ChineseColor(name: "暗蓝", pinyin: "anlan", hex: "101f30", category: .group6),
        ChineseColor(name: "鸽蓝", pinyin: "gelan", hex: "1c2938", category: .group6),
        ChineseColor(name: "青灰", pinyin: "qinghui", hex: "2b333e", category: .group6),
        ChineseColor(name: "鲸鱼灰", pinyin: "jingyuhui", hex: "475164", category: .group6),
        ChineseColor(name: "燕颔蓝", pinyin: "yanhanlan", hex: "131824", category: .group6),
        ChineseColor(name: "钢蓝", pinyin: "ganglan", hex: "0f1423", category: .group6),
        ChineseColor(name: "鱼尾灰", pinyin: "yuweihui", hex: "5e616d", category: .group6),
        ChineseColor(name: "牛角灰", pinyin: "niujiaohui", hex: "2d2e36", category: .group6),
        ChineseColor(name: "山梗紫", pinyin: "shangengzi", hex: "61649f", category: .group6),
        ChineseColor(name: "淡蓝紫", pinyin: "danlanzi", hex: "a7a8bd", category: .group6),
        ChineseColor(name: "满天星紫", pinyin: "mantianxingzi", hex: "2e317c", category: .group6),
        ChineseColor(name: "晶石紫", pinyin: "jingshizi", hex: "1f2040", category: .group6),

        // 晴岚 (52 colors)
        ChineseColor(name: "螺钿紫", pinyin: "luodianzi", hex: "74759b", category: .group7),
        ChineseColor(name: "野菊紫", pinyin: "yejuzi", hex: "525288", category: .group7),
        ChineseColor(name: "水牛灰", pinyin: "shuiniuhui", hex: "2f2f35", category: .group7),
        ChineseColor(name: "野葡萄紫", pinyin: "yeputaozi", hex: "302f4b", category: .group7),
        ChineseColor(name: "暗蓝紫", pinyin: "anlanzi", hex: "131124", category: .group7),
        ChineseColor(name: "暗龙胆紫", pinyin: "anlongdanzi", hex: "22202e", category: .group7),
        ChineseColor(name: "藤萝紫", pinyin: "tengluozi", hex: "8076a3", category: .group7),
        ChineseColor(name: "沙鱼灰", pinyin: "shayuhui", hex: "35333c", category: .group7),
        ChineseColor(name: "龙葵紫", pinyin: "longkuizi", hex: "322f3b", category: .group7),
        ChineseColor(name: "锦紫", pinyin: "jinzi", hex: "806d9e", category: .group7),
        ChineseColor(name: "茈紫", pinyin: "xunzi", hex: "815c94", category: .group7),
        ChineseColor(name: "剑锋紫", pinyin: "jianfengzi", hex: "3e3841", category: .group7),
        ChineseColor(name: "淡牵牛紫", pinyin: "danqianniuzi", hex: "d1c2d3", category: .group7),
        ChineseColor(name: "桔梗紫", pinyin: "jiegengzi", hex: "813c85", category: .group7),
        ChineseColor(name: "乌梅紫", pinyin: "wumeizi", hex: "1e131d", category: .group7),
        ChineseColor(name: "魏紫", pinyin: "weizi", hex: "7e1671", category: .group7),
        ChineseColor(name: "深牵牛紫", pinyin: "shenqianniuzi", hex: "1c0d1a", category: .group7),
        ChineseColor(name: "凤信紫", pinyin: "fengxinzi", hex: "c8adc4", category: .group7),
        ChineseColor(name: "芥花紫", pinyin: "jiehuazi", hex: "983680", category: .group7),
        ChineseColor(name: "青莲", pinyin: "qinglian", hex: "8b2671", category: .group7),
        ChineseColor(name: "葛巾紫", pinyin: "gejinzi", hex: "7e2065", category: .group7),
        ChineseColor(name: "糈紫", pinyin: "zizi", hex: "894276", category: .group7),
        ChineseColor(name: "牵牛紫", pinyin: "qianniuzi", hex: "681752", category: .group7),
        ChineseColor(name: "扁豆紫", pinyin: "biandouzi", hex: "a35c8f", category: .group7),
        ChineseColor(name: "豆蔻紫", pinyin: "doukouzi", hex: "ad6598", category: .group7),
        ChineseColor(name: "蓓蕾紫", pinyin: "biqizi", hex: "411c35", category: .group7),
        ChineseColor(name: "罗兰紫", pinyin: "luolanzi", hex: "c08eaf", category: .group7),
        ChineseColor(name: "青壳紫", pinyin: "qinghakezi", hex: "bc84a8", category: .group7),
        ChineseColor(name: "龙睛鱼紫", pinyin: "longjingyuzi", hex: "4e2a40", category: .group7),
        ChineseColor(name: "紫灰", pinyin: "zihui", hex: "5d3f51", category: .group7),
        ChineseColor(name: "苋菜紫", pinyin: "xiancaizi", hex: "9b1e64", category: .group7),
        ChineseColor(name: "玫瑰紫", pinyin: "meiguizi", hex: "ba2f7b", category: .group7),
        ChineseColor(name: "电气石红", pinyin: "dianqishihong", hex: "c35691", category: .group7),
        ChineseColor(name: "龙须红", pinyin: "longxuhong", hex: "cc5595", category: .group7),
        ChineseColor(name: "樱桃草紫", pinyin: "yingcaozi", hex: "c06f98", category: .group7),
        ChineseColor(name: "棱锰红", pinyin: "lingmenghong", hex: "d276a3", category: .group7),
        ChineseColor(name: "古鼎灰", pinyin: "gudinghui", hex: "36292f", category: .group7),
        ChineseColor(name: "玫瑰红", pinyin: "meiguihong", hex: "d2357d", category: .group7),
        ChineseColor(name: "丹紫红", pinyin: "danzihong", hex: "d2568c", category: .group7),
        ChineseColor(name: "古铜紫", pinyin: "gutongzi", hex: "440e25", category: .group7),
        ChineseColor(name: "斑鸠灰", pinyin: "banjiuhui", hex: "482936", category: .group7),
        ChineseColor(name: "藏花红", pinyin: "canghuahong", hex: "ec2d7a", category: .group7),
        ChineseColor(name: "扁豆花红", pinyin: "biandouhuahong", hex: "ef498b", category: .group7),
        ChineseColor(name: "紫荆红", pinyin: "zijinghong", hex: "ee2c79", category: .group7),
        ChineseColor(name: "干紫", pinyin: "ganzi", hex: "461629", category: .group7),
        ChineseColor(name: "吊钟花红", pinyin: "diaozhonghuahong", hex: "ce5e8a", category: .group7),
        ChineseColor(name: "洋葱紫", pinyin: "yangcongzi", hex: "a8456b", category: .group7),
        ChineseColor(name: "嫩菱红", pinyin: "nenlinghong", hex: "de3f7c", category: .group7),
        ChineseColor(name: "兔眼红", pinyin: "tuyanhong", hex: "ec4e8a", category: .group7),
        ChineseColor(name: "海象紫", pinyin: "haixiangzi", hex: "4b1e2f", category: .group7),
        ChineseColor(name: "博根红", pinyin: "bogenhong", hex: "d13c74", category: .group7),
        ChineseColor(name: "淡青紫", pinyin: "danqingzi", hex: "e0c8d1", category: .group7),

        // 暮山 (52 colors)
        ChineseColor(name: "葡萄酒紫", pinyin: "putaojiuhong", hex: "62102e", category: .group8),
        ChineseColor(name: "菜头紫", pinyin: "caitouzi", hex: "951c48", category: .group8),
        ChineseColor(name: "初荷红", pinyin: "chuhehong", hex: "e16c96", category: .group8),
        ChineseColor(name: "檀紫", pinyin: "tanzi", hex: "381924", category: .group8),
        ChineseColor(name: "墨紫", pinyin: "mozi", hex: "310f1b", category: .group8),
        ChineseColor(name: "磨石紫", pinyin: "moshizi", hex: "382129", category: .group8),
        ChineseColor(name: "品红", pinyin: "pinhong", hex: "ef3473", category: .group8),
        ChineseColor(name: "鹦鹉紫", pinyin: "yaoguanzi", hex: "621d34", category: .group8),
        ChineseColor(name: "火鹤紫", pinyin: "huoezi", hex: "33141e", category: .group8),
        ChineseColor(name: "醋酱草红", pinyin: "cujiangcaohong", hex: "c5708b", category: .group8),
        ChineseColor(name: "晚波红", pinyin: "wenpohong", hex: "ed2f6a", category: .group8),
        ChineseColor(name: "隐红灰", pinyin: "yinhonghui", hex: "b598a1", category: .group8),
        ChineseColor(name: "白芨红", pinyin: "baijihong", hex: "de7897", category: .group8),
        ChineseColor(name: "莲瓣红", pinyin: "lianbanhong", hex: "ea517f", category: .group8),
        ChineseColor(name: "松叶牡丹红", pinyin: "songyemudanhong", hex: "eb3c70", category: .group8),
        ChineseColor(name: "夹竹桃红", pinyin: "jiazhutaohong", hex: "eb507e", category: .group8),
        ChineseColor(name: "喜蛋红", pinyin: "xidanhong", hex: "ec2c64", category: .group8),
        ChineseColor(name: "霞光红", pinyin: "xiaguanghong", hex: "ef82a0", category: .group8),
        ChineseColor(name: "凤仙花红", pinyin: "fengxianhuahong", hex: "ea7293", category: .group8),
        ChineseColor(name: "淡绛红", pinyin: "danjianghong", hex: "ec7696", category: .group8),
        ChineseColor(name: "报春红", pinyin: "baochunhong", hex: "ec8aa4", category: .group8),
        ChineseColor(name: "豇豆红", pinyin: "jiangdouhong", hex: "ed9db2", category: .group8),
        ChineseColor(name: "暮云灰", pinyin: "muyunhui", hex: "4f383e", category: .group8),
        ChineseColor(name: "芍药耕红", pinyin: "shaoyaogenghong", hex: "eba0b3", category: .group8),
        ChineseColor(name: "芝兰紫", pinyin: "zhilanzi", hex: "e9ccd3", category: .group8),
        ChineseColor(name: "晶红", pinyin: "jinghong", hex: "eea6b7", category: .group8),
        ChineseColor(name: "卵石紫", pinyin: "luanshizi", hex: "30161c", category: .group8),
        ChineseColor(name: "石竹紫", pinyin: "shizhuzi", hex: "63071c", category: .group8),
        ChineseColor(name: "粉团花红", pinyin: "fentuanhuahong", hex: "ec9bad", category: .group8),
        ChineseColor(name: "锦葵红", pinyin: "jinkuihong", hex: "bf3553", category: .group8),
        ChineseColor(name: "苍蝇灰", pinyin: "cangyinghui", hex: "36282b", category: .group8),
        ChineseColor(name: "荞麦皮紫", pinyin: "qiepizi", hex: "2d0c13", category: .group8),
        ChineseColor(name: "芦灰", pinyin: "luhui", hex: "856d72", category: .group8),
        ChineseColor(name: "姜红", pinyin: "jianghong", hex: "eeb8c3", category: .group8),
        ChineseColor(name: "水红", pinyin: "shuihong", hex: "f1c4cd", category: .group8),
        ChineseColor(name: "尖晶玉红", pinyin: "jianjingyuhong", hex: "cc163a", category: .group8),
        ChineseColor(name: "月季红", pinyin: "yuejihong", hex: "ce5777", category: .group8),
        ChineseColor(name: "甘蔗紫", pinyin: "ganzhezi", hex: "621624", category: .group8),
        ChineseColor(name: "淡瑞香红", pinyin: "danruixianghong", hex: "ee4866", category: .group8),
        ChineseColor(name: "鼠背灰", pinyin: "shubeihui", hex: "73575c", category: .group8),
        ChineseColor(name: "金鱼紫", pinyin: "jinyuzi", hex: "500a16", category: .group8),
        ChineseColor(name: "山踯躅红", pinyin: "shanlidouhong", hex: "c27c88", category: .group8),
        ChineseColor(name: "淡茜红", pinyin: "danqianhong", hex: "e77c8e", category: .group8),
        ChineseColor(name: "石竹红", pinyin: "shizhuhong", hex: "ee4863", category: .group8),
        ChineseColor(name: "李紫", pinyin: "lizi", hex: "2b1216", category: .group8),
        ChineseColor(name: "淡曙红", pinyin: "danshuhong", hex: "ee2746", category: .group8),
        ChineseColor(name: "石蕊红", pinyin: "shiruihong", hex: "f0c9cf", category: .group8),
        ChineseColor(name: "济粉红", pinyin: "jifenhong", hex: "e6d2d5", category: .group8),
        ChineseColor(name: "海棠红", pinyin: "haitanghong", hex: "f03752", category: .group8),
        ChineseColor(name: "山茶红", pinyin: "shanchahong", hex: "ed556a", category: .group8),
        ChineseColor(name: "酱紫", pinyin: "jiangzi", hex: "4d1018", category: .group8),
        ChineseColor(name: "草茉莉红", pinyin: "caomolihong", hex: "ef475d", category: .group8),

        // 桃夭 (52 colors)
        ChineseColor(name: "构树红", pinyin: "goushuhong", hex: "ed3333", category: .group9),
        ChineseColor(name: "鸟紫", pinyin: "diaozi", hex: "5d3131", category: .group9),
        ChineseColor(name: "淡曙红", pinyin: "danshuhong", hex: "ed4845", category: .group9),
        ChineseColor(name: "玫瑰灰", pinyin: "meiguihui", hex: "4b2e2b", category: .group9),
        ChineseColor(name: "淡绯", pinyin: "danfei", hex: "f2cac9", category: .group9),
        ChineseColor(name: "无花果红", pinyin: "wuhuaguohong", hex: "efafad", category: .group9),
        ChineseColor(name: "秋海棠红", pinyin: "qiuhaitanghong", hex: "ec2b24", category: .group9),
        ChineseColor(name: "榴子红", pinyin: "liuzihong", hex: "f1908c", category: .group9),
        ChineseColor(name: "豆沙", pinyin: "dousha", hex: "481e1c", category: .group9),
        ChineseColor(name: "海豹灰", pinyin: "haibaohui", hex: "483332", category: .group9),
        ChineseColor(name: "覆盆子红", pinyin: "fupenzihong", hex: "ac1f18", category: .group9),
        ChineseColor(name: "丽春红", pinyin: "lichunhong", hex: "eb261a", category: .group9),
        ChineseColor(name: "芦穗灰", pinyin: "lusuihui", hex: "bdaead", category: .group9),
        ChineseColor(name: "鱼鳃红", pinyin: "yusaihong", hex: "ed3b2f", category: .group9),
        ChineseColor(name: "酱棕", pinyin: "jiangzong", hex: "5a1f1b", category: .group9),
        ChineseColor(name: "鹅血石红", pinyin: "exueshihong", hex: "ab372f", category: .group9),
        ChineseColor(name: "舌红", pinyin: "shehong", hex: "f19790", category: .group9),
        ChineseColor(name: "鹤顶红", pinyin: "hedinghong", hex: "d42517", category: .group9),
        ChineseColor(name: "栗棕", pinyin: "lizong", hex: "5c1e19", category: .group9),
        ChineseColor(name: "火山棕", pinyin: "huoshanzong", hex: "482522", category: .group9),
        ChineseColor(name: "珊瑚红", pinyin: "shanhuhong", hex: "f04a3a", category: .group9),
        ChineseColor(name: "樱桃红", pinyin: "yingtaohong", hex: "ed3321", category: .group9),
        ChineseColor(name: "夕阳红", pinyin: "xiyanghong", hex: "de2a18", category: .group9),
        ChineseColor(name: "暗驼棕", pinyin: "antuozong", hex: "592620", category: .group9),
        ChineseColor(name: "粉红", pinyin: "fenhong", hex: "f2b9b2", category: .group9),
        ChineseColor(name: "桂红", pinyin: "guihong", hex: "f25a47", category: .group9),
        ChineseColor(name: "苹果红", pinyin: "pingguohong", hex: "f15642", category: .group9),
        ChineseColor(name: "古桥红", pinyin: "guqiaohong", hex: "f17666", category: .group9),
        ChineseColor(name: "曲红", pinyin: "quhong", hex: "f05a46", category: .group9),
        ChineseColor(name: "萝卜红", pinyin: "luobohong", hex: "f13c22", category: .group9),
        ChineseColor(name: "红工红", pinyin: "honggonghong", hex: "f23e23", category: .group9),
        ChineseColor(name: "极光红", pinyin: "jiguanghong", hex: "f33b1f", category: .group9),
        ChineseColor(name: "胭脂红", pinyin: "yanzhihong", hex: "f03f24", category: .group9),
        ChineseColor(name: "铁水红", pinyin: "tieshuihong", hex: "f5391c", category: .group9),
        ChineseColor(name: "赭石", pinyin: "zheshi", hex: "862617", category: .group9),
        ChineseColor(name: "火岩棕", pinyin: "huoyanzong", hex: "863020", category: .group9),
        ChineseColor(name: "桃红", pinyin: "taohong", hex: "f0ada0", category: .group9),
        ChineseColor(name: "颊红", pinyin: "jiahong", hex: "eeaa9c", category: .group9),
        ChineseColor(name: "橡树棕", pinyin: "xiangshuzong", hex: "773d31", category: .group9),
        ChineseColor(name: "蜻蜓红", pinyin: "qingtinghong", hex: "f1441d", category: .group9),
        ChineseColor(name: "柘叶棕", pinyin: "zhayezong", hex: "692a1b", category: .group9),
        ChineseColor(name: "大红", pinyin: "dahong", hex: "f04b22", category: .group9),
        ChineseColor(name: "淡胭脂红", pinyin: "danyingsuhong", hex: "eea08c", category: .group9),
        ChineseColor(name: "可可棕", pinyin: "kekezong", hex: "652b1c", category: .group9),
        ChineseColor(name: "柿红", pinyin: "shihong", hex: "f2481b", category: .group9),
        ChineseColor(name: "榴花红", pinyin: "liuhuahong", hex: "f34718", category: .group9),
        ChineseColor(name: "朱红", pinyin: "zhuhong", hex: "ed5126", category: .group9),
        ChineseColor(name: "洋水仙红", pinyin: "yangshuixianhong", hex: "f4c7ba", category: .group9),
        ChineseColor(name: "草莓红", pinyin: "caomeihong", hex: "ef6f48", category: .group9),
        ChineseColor(name: "银朱", pinyin: "yinzhu", hex: "f43e06", category: .group9),
        ChineseColor(name: "淡栗棕", pinyin: "danlizong", hex: "673424", category: .group9),
        ChineseColor(name: "石板灰", pinyin: "shibanhui", hex: "624941", category: .group9),

    ]

    static let defaultBrandColor = ChineseColor(
        name: "粉绿",
        pinyin: "fenlv",
        hex: "83cbac",
        category: .group5
    )

    /// Pre-grouped colors by category — avoids linear scan of allColors for filtering
    static let colorsByCategory: [ChineseColor.ColorCategory: [ChineseColor]] = {
        Dictionary(grouping: allColors, by: { $0.category })
    }()
}
